spring.application.name=agendador-horarios

# URL para criar o banco em memória chamado 'agendador'
spring.datasource.url=jdbc:h2:mem:agendador
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# O Spring Boot atual (versão 3+) não precisa mais que você especifique o dialect do H2 manualmente, ele descobre sozinho.
# spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Configurações do Console do H2 (Acessível via http://localhost:8080/h2-console)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console